# This file was generated by GoReleaser. DO NOT EDIT.
cask "awtest" do
  name "awtest"
  desc "AWS credential enumeration for security assessments"
  homepage "https://github.com/MillerMedia/awtest"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awtest"

  on_macos do
    on_intel do
      url "https://github.com/MillerMedia/awtest/releases/download/v#{version}/awtest_#{version}_darwin_amd64.tar.gz"
      sha256 "afb03c42962c7202f5f0c5c8205f474d26a6ba9d823de680eca5b5ba85ea1cbe"
    end
    on_arm do
      url "https://github.com/MillerMedia/awtest/releases/download/v#{version}/awtest_#{version}_darwin_arm64.tar.gz"
      sha256 "c926b13e8bb747fdd70b8561ef20f2a7a0ba89d6d5e2cfb09505bd8173bac0bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MillerMedia/awtest/releases/download/v#{version}/awtest_#{version}_linux_amd64.tar.gz"
      sha256 "ee4f94451649d1a0b0048d5285f44dd94620192b49b66901958d4e3c68da093d"
    end
    on_arm do
      url "https://github.com/MillerMedia/awtest/releases/download/v#{version}/awtest_#{version}_linux_arm64.tar.gz"
      sha256 "3ec166a6be3d60f37a438e268a3df2939bbccfd092194d2c39b5d3299c2755bf"
    end
  end

  # No zap stanza required
end
